# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Feed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Feed.proto',
  package='sale',
  syntax='proto2',
  serialized_pb=_b('\n\nFeed.proto\x12\x04sale\"Z\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x12\n\nfull_title\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\x12\x15\n\runiform_title\x18\x04 \x01(\t\x12\r\n\x05\x65\x61n13\x18\x05 \x01(\t\"b\n\tSaleImage\x12\x1b\n\x07sale_id\x18\x01 \x02(\x0b\x32\n.sale.Sale\x12\x10\n\x08img_type\x18\x02 \x01(\t\x12\x12\n\nimage_name\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x05\"\x9d\x02\n\x04Sale\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x11\n\tseller_id\x18\x02 \x02(\t\x12\x17\n\x0fseller_username\x18\x03 \x01(\t\x12\x18\n\x04\x62ook\x18\x04 \x01(\x0b\x32\n.sale.Book\x12\x12\n\ndesription\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\t\x12\x10\n\x08location\x18\x07 \x01(\t\x12\x10\n\x08latitude\x18\x08 \x01(\x01\x12\x11\n\tlongitude\x18\t \x01(\x01\x12\x0c\n\x04sold\x18\n \x01(\x08\x12\x12\n\ncategories\x18\x0b \x01(\t\x12\x12\n\ncreated_at\x18\x0c \x01(\x05\x12\x12\n\nextra_info\x18\r \x01(\t\x12\x1f\n\x06images\x18\x0e \x03(\x0b\x32\x0f.sale.SaleImage\"!\n\x04\x46\x65\x65\x64\x12\x19\n\x05sales\x18\x01 \x03(\x0b\x32\n.sale.Sale')
)




_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='sale.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sale.Book.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_title', full_name='sale.Book.full_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link', full_name='sale.Book.link', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uniform_title', full_name='sale.Book.uniform_title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ean13', full_name='sale.Book.ean13', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=110,
)


_SALEIMAGE = _descriptor.Descriptor(
  name='SaleImage',
  full_name='sale.SaleImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sale_id', full_name='sale.SaleImage.sale_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_type', full_name='sale.SaleImage.img_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_name', full_name='sale.SaleImage.image_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='sale.SaleImage.created_at', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=210,
)


_SALE = _descriptor.Descriptor(
  name='Sale',
  full_name='sale.Sale',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sale.Sale.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seller_id', full_name='sale.Sale.seller_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seller_username', full_name='sale.Sale.seller_username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='book', full_name='sale.Sale.book', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desription', full_name='sale.Sale.desription', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='sale.Sale.price', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='sale.Sale.location', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='sale.Sale.latitude', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='sale.Sale.longitude', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sold', full_name='sale.Sale.sold', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categories', full_name='sale.Sale.categories', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='sale.Sale.created_at', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_info', full_name='sale.Sale.extra_info', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='sale.Sale.images', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=498,
)


_FEED = _descriptor.Descriptor(
  name='Feed',
  full_name='sale.Feed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sales', full_name='sale.Feed.sales', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=533,
)

_SALEIMAGE.fields_by_name['sale_id'].message_type = _SALE
_SALE.fields_by_name['book'].message_type = _BOOK
_SALE.fields_by_name['images'].message_type = _SALEIMAGE
_FEED.fields_by_name['sales'].message_type = _SALE
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['SaleImage'] = _SALEIMAGE
DESCRIPTOR.message_types_by_name['Sale'] = _SALE
DESCRIPTOR.message_types_by_name['Feed'] = _FEED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), dict(
  DESCRIPTOR = _BOOK,
  __module__ = 'Feed_pb2'
  # @@protoc_insertion_point(class_scope:sale.Book)
  ))
_sym_db.RegisterMessage(Book)

SaleImage = _reflection.GeneratedProtocolMessageType('SaleImage', (_message.Message,), dict(
  DESCRIPTOR = _SALEIMAGE,
  __module__ = 'Feed_pb2'
  # @@protoc_insertion_point(class_scope:sale.SaleImage)
  ))
_sym_db.RegisterMessage(SaleImage)

Sale = _reflection.GeneratedProtocolMessageType('Sale', (_message.Message,), dict(
  DESCRIPTOR = _SALE,
  __module__ = 'Feed_pb2'
  # @@protoc_insertion_point(class_scope:sale.Sale)
  ))
_sym_db.RegisterMessage(Sale)

Feed = _reflection.GeneratedProtocolMessageType('Feed', (_message.Message,), dict(
  DESCRIPTOR = _FEED,
  __module__ = 'Feed_pb2'
  # @@protoc_insertion_point(class_scope:sale.Feed)
  ))
_sym_db.RegisterMessage(Feed)


# @@protoc_insertion_point(module_scope)
