# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_sale_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleimage',
            name='img_type',
            field=models.CharField(default=b'', max_length=16),
        ),
        migrations.AlterField(
            model_name='salenotification',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salenotification',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
